/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dbinterface.DBInterface;
import java.awt.Color;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manuel
 */
public class WikiStarterGUI extends javax.swing.JPanel {

    /**
     * Creates new form WikiStarterGUI
     */
    public WikiStarterGUI() {
        initComponents();
        db = new DBInterface();
        LoginPanel.setVisible(true);
        MainPanel.setVisible(false);
        PersonalArea.setVisible(false);
        lastPressed = null;
        globalID = "1";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        UsernameFld = new javax.swing.JTextField();
        PassworfFld = new javax.swing.JPasswordField();
        UsernameLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        RegisterBtn = new javax.swing.JButton();
        TitleTxtF = new javax.swing.JTextField();
        ErrorLbl = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        UsernameTxtF = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        TitleTxtF1 = new javax.swing.JTextField();
        PrjLst = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PrjTblLbl = new javax.swing.JLabel();
        ListActiveBtn = new javax.swing.JButton();
        ListOldBtn = new javax.swing.JButton();
        ListOwnBtn = new javax.swing.JButton();
        ListAllBtn = new javax.swing.JButton();
        PledgeBtn = new javax.swing.JButton();
        BalanceLbl = new javax.swing.JLabel();
        DescTxtArea = new javax.swing.JLabel();
        AmmountFld = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        MessageTxtArea = new javax.swing.JTextArea();
        SendMsgLbl = new javax.swing.JLabel();
        SendBtn = new javax.swing.JToggleButton();
        StatusLbl = new javax.swing.JLabel();
        PrjIdLbl = new javax.swing.JLabel();
        PrjNameLbl = new javax.swing.JLabel();
        PrjOwnerLbl = new javax.swing.JLabel();
        PrjDueLbl = new javax.swing.JLabel();
        PrjObjLbl = new javax.swing.JLabel();
        PrjAmmoutLbl = new javax.swing.JLabel();
        PersonalAreaBtn = new javax.swing.JButton();
        OpenTxtFld = new javax.swing.JTextField();
        OpenPrjBtn = new javax.swing.JButton();
        BalanceLbl2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        RewardsArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonRf = new javax.swing.JButton();
        PersonalArea = new javax.swing.JPanel();
        LogoutBtn1 = new javax.swing.JButton();
        MainAreaBtn = new javax.swing.JButton();
        UsernameTxtF1 = new javax.swing.JLabel();
        TitleTxtF2 = new javax.swing.JTextField();
        PrjLst1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        CreatePrjBtn = new javax.swing.JButton();
        ListOwnBtnP = new javax.swing.JButton();
        UsernameTxtFPA = new javax.swing.JLabel();
        StatusLblPA = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonReply = new javax.swing.JButton();
        jButtonGM = new javax.swing.JButton();
        jButtonGM1 = new javax.swing.JButton();
        PrjNameLbl1 = new javax.swing.JLabel();
        PrjDueLbl1 = new javax.swing.JLabel();
        PrjObjLbl1 = new javax.swing.JLabel();
        jTextFieldObjective = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jTextFieldDue = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        CancelProj = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setLayout(new java.awt.CardLayout());

        LoginPanel.setMaximumSize(new java.awt.Dimension(600, 500));
        LoginPanel.setMinimumSize(new java.awt.Dimension(600, 500));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        LoginPanel.add(UsernameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 175, 335, -1));
        LoginPanel.add(PassworfFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 201, 334, -1));

        UsernameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsernameLbl.setText("Username:");
        LoginPanel.add(UsernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 175, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password: ");
        jLabel2.setToolTipText("");
        LoginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 201, -1, -1));

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        LoginPanel.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 293, 100, 45));

        RegisterBtn.setText("Register");
        RegisterBtn.setToolTipText("");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        LoginPanel.add(RegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 293, 100, 45));

        TitleTxtF.setEditable(false);
        TitleTxtF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitleTxtF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TitleTxtF.setText("WikiStarter");
        LoginPanel.add(TitleTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 11, 160, 49));

        ErrorLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ErrorLbl.setForeground(new java.awt.Color(255, 0, 0));
        ErrorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPanel.add(ErrorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 550, 120));

        add(LoginPanel, "card2");

        MainPanel.setToolTipText("");
        MainPanel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MainPanel.setMaximumSize(new java.awt.Dimension(600, 500));
        MainPanel.setMinimumSize(new java.awt.Dimension(600, 500));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameTxtF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UsernameTxtF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(UsernameTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        MainPanel.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, -1));

        TitleTxtF1.setEditable(false);
        TitleTxtF1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitleTxtF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TitleTxtF1.setText("WikiStarter");
        MainPanel.add(TitleTxtF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 160, 49));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Project Name", "Project Owner", "Due Date", "Ammount Earned", "Objective"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PrjLst.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        MainPanel.add(PrjLst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 580, 130));

        PrjTblLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrjTblLbl.setText("Projects");
        MainPanel.add(PrjTblLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        ListActiveBtn.setText("List Active");
        ListActiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListActiveBtnActionPerformed(evt);
            }
        });
        MainPanel.add(ListActiveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, -1));

        ListOldBtn.setText("List Old");
        ListOldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOldBtnActionPerformed(evt);
            }
        });
        MainPanel.add(ListOldBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, -1));

        ListOwnBtn.setText("List Owned");
        ListOwnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOwnBtnActionPerformed(evt);
            }
        });
        MainPanel.add(ListOwnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 140, -1));

        ListAllBtn.setText("List All");
        ListAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListAllBtnActionPerformed(evt);
            }
        });
        MainPanel.add(ListAllBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 140, -1));

        PledgeBtn.setText("Pledge");
        PledgeBtn.setToolTipText("");
        PledgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PledgeBtnActionPerformed(evt);
            }
        });
        MainPanel.add(PledgeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 131, -1));

        BalanceLbl.setText("Balance:");
        MainPanel.add(BalanceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 50, 20));

        DescTxtArea.setText("Rewards:");
        MainPanel.add(DescTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 160, 20));

        AmmountFld.setText("Ammount");
        MainPanel.add(AmmountFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 131, -1));

        MessageTxtArea.setColumns(20);
        MessageTxtArea.setRows(5);
        jScrollPane2.setViewportView(MessageTxtArea);

        MainPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 190, 50));

        SendMsgLbl.setText("Send Message:");
        SendMsgLbl.setToolTipText("");
        MainPanel.add(SendMsgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 424, 80, 20));

        SendBtn.setText("SEND");
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));
        MainPanel.add(StatusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 200, 30));

        PrjIdLbl.setText("ID");
        MainPanel.add(PrjIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 131, -1));

        PrjNameLbl.setText("Name");
        MainPanel.add(PrjNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 131, -1));

        PrjOwnerLbl.setText("Owner");
        MainPanel.add(PrjOwnerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 131, -1));

        PrjDueLbl.setText("Due Date");
        MainPanel.add(PrjDueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 131, -1));

        PrjObjLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrjObjLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrjObjLbl.setText("Objective");
        MainPanel.add(PrjObjLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 131, 20));

        PrjAmmoutLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrjAmmoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrjAmmoutLbl.setText("Ammout");
        MainPanel.add(PrjAmmoutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 131, 40));

        PersonalAreaBtn.setText("Personal Area");
        PersonalAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalAreaBtnActionPerformed(evt);
            }
        });
        MainPanel.add(PersonalAreaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, -1));

        OpenTxtFld.setText("1");
        OpenTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenTxtFldActionPerformed(evt);
            }
        });
        MainPanel.add(OpenTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, -1));

        OpenPrjBtn.setText("Open Project");
        OpenPrjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenPrjBtnActionPerformed(evt);
            }
        });
        MainPanel.add(OpenPrjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, -1));

        BalanceLbl2.setBackground(new java.awt.Color(255, 255, 255));
        BalanceLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BalanceLbl2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MainPanel.add(BalanceLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 70, 20));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        DescriptionArea.setColumns(20);
        DescriptionArea.setRows(5);
        jScrollPane1.setViewportView(DescriptionArea);

        MainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 430, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Don't Forget to Vote!!");
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        RewardsArea.setColumns(20);
        RewardsArea.setRows(5);
        jScrollPane5.setViewportView(RewardsArea);

        MainPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 430, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("C'Mon GIVE!");
        MainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 210, 100));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "", "", "", "", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList1);

        MainPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 210, 50));

        jButtonRf.setText("Refresh Database");
        jButtonRf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRfActionPerformed(evt);
            }
        });
        MainPanel.add(jButtonRf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        add(MainPanel, "card3");

        PersonalArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PersonalArea.setMaximumSize(new java.awt.Dimension(600, 500));
        PersonalArea.setMinimumSize(new java.awt.Dimension(600, 500));
        PersonalArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutBtn1.setText("Logout");
        LogoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtn1ActionPerformed(evt);
            }
        });
        PersonalArea.add(LogoutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, -1));

        MainAreaBtn.setText("Main Area");
        MainAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainAreaBtnActionPerformed(evt);
            }
        });
        PersonalArea.add(MainAreaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, -1));

        UsernameTxtF1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PersonalArea.add(UsernameTxtF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        TitleTxtF2.setEditable(false);
        TitleTxtF2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitleTxtF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TitleTxtF2.setText("WikiStarter");
        PersonalArea.add(TitleTxtF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 160, 49));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Project Name", "Project Owner", "Due Date", "Ammount Earned", "Objective"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PrjLst1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        PersonalArea.add(PrjLst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 590, 130));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Personal Area");
        PersonalArea.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 50, 160, 20));

        CreatePrjBtn.setText("New Project");
        CreatePrjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePrjBtnActionPerformed(evt);
            }
        });
        PersonalArea.add(CreatePrjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 120, 30));

        ListOwnBtnP.setText("Refresh List");
        ListOwnBtnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOwnBtnPActionPerformed(evt);
            }
        });
        PersonalArea.add(ListOwnBtnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, -1));

        UsernameTxtFPA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UsernameTxtFPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonalArea.add(UsernameTxtFPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));
        PersonalArea.add(StatusLblPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 200, 30));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        PersonalArea.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 280, 40));

        jScrollPane4.setFocusable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Reply");
        jScrollPane4.setViewportView(jTextArea1);

        PersonalArea.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 280, 50));

        jScrollPane7.setFocusable(false);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Message");
        jScrollPane7.setViewportView(jTextArea2);

        PersonalArea.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 280, 40));

        jButtonReply.setText("Reply");
        jButtonReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReplyActionPerformed(evt);
            }
        });
        PersonalArea.add(jButtonReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 90, -1));

        jButtonGM.setText("Get");
        jButtonGM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGMActionPerformed(evt);
            }
        });
        PersonalArea.add(jButtonGM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 70, -1));

        jButtonGM1.setText("Open");
        jButtonGM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGM1ActionPerformed(evt);
            }
        });
        PersonalArea.add(jButtonGM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 70, -1));

        PrjNameLbl1.setText("Name");
        PersonalArea.add(PrjNameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, -1));

        PrjDueLbl1.setText("Due Date");
        PersonalArea.add(PrjDueLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 60, -1));

        PrjObjLbl1.setText("Objective");
        PersonalArea.add(PrjObjLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));
        PersonalArea.add(jTextFieldObjective, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, -1));
        PersonalArea.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 200, -1));

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane8.setViewportView(jTextAreaDescription);

        PersonalArea.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 270, 80));

        jTextFieldDue.setText("YY-MM-DD");
        PersonalArea.add(jTextFieldDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 200, -1));

        jTextField1.setText("Name");
        PersonalArea.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 410, 110, 20));

        jTextField2.setText("Value");
        PersonalArea.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 60, 20));

        jTextField3.setText("Vote Option");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        PersonalArea.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 170, -1));

        jButton1.setText("Add Reward");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PersonalArea.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 120, 20));

        jButton2.setText("Add Option");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PersonalArea.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 120, 20));

        jLabel5.setText("Selected Project:");
        PersonalArea.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");
        PersonalArea.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 374, 30, 30));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane9.setViewportView(jTextArea3);

        PersonalArea.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 280, 70));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mail Area");
        PersonalArea.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 280, -1));

        CancelProj.setForeground(new java.awt.Color(255, 0, 0));
        CancelProj.setText("Cancel Project!");
        CancelProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelProjActionPerformed(evt);
            }
        });
        PersonalArea.add(CancelProj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 120, 30));

        add(PersonalArea, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String name = UsernameFld.getText();
        String pswd = String.valueOf(PassworfFld.getPassword());
        System.out.println(pswd);
        String result = db.login(name, pswd);

        if (result.contains("user_found")) {
            LoginPanel.setVisible(false);
            MainPanel.setVisible(true);
            PersonalArea.setVisible(false);
            UsernameTxtF.setText(name);
            ResultSet rs = db.listaProjetosActuaisRS();
            DefaultTableModel T;
            T = returndata(rs);
            jTable1.setModel(T);
            PrjLst.getViewport().add(jTable1);
            BalanceLbl2.setText(db.consultarSaldo(name));
            lastPressed = ListActiveBtn;
        } else if (result.contains("wrong_password")) {
            ErrorLbl.setForeground(Color.RED);
            ErrorLbl.setText("WRONG PASSWORD");
        } else if (result.contains("unknown_user")) {
            ErrorLbl.setForeground(Color.RED);
            ErrorLbl.setText("UNKNOWN USER");
        }
        //System.out.println("ERRO: LOGIN NÃO RECONHECIDO");
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        String name = UsernameFld.getText();
        String pswd = String.valueOf(PassworfFld.getPassword());
        if (!name.isEmpty()) {
            String result = db.addUser(name, pswd);
            if (result.contains("user_found")) {
                ErrorLbl.setForeground(Color.BLUE);
                ErrorLbl.setText("Already Exists Choose Another Username");
            } else if (result.contains("accepted_new_user")) {
                ErrorLbl.setForeground(Color.GREEN);
                ErrorLbl.setText("Acepted, Please hit Login");
            }
        }
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        LoginPanel.setVisible(true);
        MainPanel.setVisible(false);
        PersonalArea.setVisible(false);
        UsernameTxtF.setText("");
        UsernameFld.setText("");
        PassworfFld.setText("");
        ErrorLbl.setText("");
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void ListActiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListActiveBtnActionPerformed
        ResultSet rs = db.listaProjetosActuaisRS();
        DefaultTableModel T;
        T = returndata(rs);
        jTable1.setModel(T);
        PrjLst.getViewport().add(jTable1);
        lastPressed = ListActiveBtn;
        jButtonRf.doClick();
    }//GEN-LAST:event_ListActiveBtnActionPerformed

    private void OpenPrjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenPrjBtnActionPerformed

        String temp = OpenTxtFld.getText();
        String rwards = db.mostrarRecompensasProjNEW(Integer.valueOf(temp));
        RewardsArea.setText(rwards);

        ResultSet rs = db.openProject(temp);

        try {
            rs.next();
            PrjIdLbl.setText("ID: " + rs.getString("idp"));
            DescriptionArea.setText(rs.getString("descricao"));
            PrjNameLbl.setText("Name: " + rs.getString("nomep"));
            PrjOwnerLbl.setText("Owner: " + rs.getString("dono"));
            PrjDueLbl.setText("Due: " + rs.getString("finall"));
            PrjObjLbl.setText("Objective: " + rs.getString("pretendido"));
            float obj = Float.valueOf(rs.getString("pretendido"));
            float saldo = Float.valueOf(rs.getString("saldop"));
            if (saldo < obj * 0.9) {
                PrjAmmoutLbl.setForeground(Color.red);
            } else if (saldo < obj && saldo > obj * 0.9) {
                PrjAmmoutLbl.setForeground(Color.yellow);
            } else if (saldo >= obj) {
                PrjAmmoutLbl.setForeground(Color.green);
            }
            PrjAmmoutLbl.setText(rs.getString("saldop"));

            DefaultListModel model;
            model = db.mostrarVotosProjLST(Integer.valueOf(rs.getString("idp")));
            jList1.setModel(model);
            jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            jList1.setSelectedIndex(0);
            jScrollPane6.getViewport().add(jList1);

        } catch (SQLException ex) {
            Logger.getLogger(WikiStarterGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_OpenPrjBtnActionPerformed

    private void PledgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PledgeBtnActionPerformed

        int flag = 0;
        try {
            Float.valueOf(AmmountFld.getText());
        } catch (NumberFormatException e) {
            flag = 1;
        }

        if (AmmountFld.getText().isEmpty() || AmmountFld.getText().contains("Ammount")) {
            StatusLbl.setForeground(Color.red);
            StatusLbl.setText("Please Choose Ammount");
        } else if (flag == 1) {
            StatusLbl.setForeground(Color.red);
            StatusLbl.setText("Not a Valid Ammout");
        } else if (Float.valueOf(AmmountFld.getText()) > Float.valueOf(BalanceLbl2.getText())) {
            StatusLbl.setForeground(Color.red);
            StatusLbl.setText("Insuficient Funds...");
        } else if (PrjIdLbl.getText().equals("ID")) {
            StatusLbl.setForeground(Color.red);
            StatusLbl.setText("No Project Selected");
        } else {
            String voto = jList1.getSelectedValue();
            try {
                StatusLbl.setText(db.doar(UsernameTxtF.getText(), Integer.valueOf(OpenTxtFld.getText()), Float.valueOf(AmmountFld.getText()), voto));
                BalanceLbl2.setText(db.consultarSaldo(UsernameTxtF.getText()));
                OpenPrjBtn.doClick();
                lastPressed.doClick();
            } catch (SQLException ex) {
                Logger.getLogger(WikiStarterGUI.class.getName()).log(Level.SEVERE, null, ex);
                StatusLbl.setText("DATABASE ERROR");
            }

        }


    }//GEN-LAST:event_PledgeBtnActionPerformed

    private void OpenTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenTxtFldActionPerformed

    private void ListOldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOldBtnActionPerformed
        ResultSet rs = db.listaProjetosAntigosRS();
        DefaultTableModel T;
        T = returndata(rs);
        jTable1.setModel(T);
        PrjLst.getViewport().add(jTable1);
        lastPressed = ListOldBtn;
        jButtonRf.doClick();
    }//GEN-LAST:event_ListOldBtnActionPerformed

    private void ListAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListAllBtnActionPerformed
        ResultSet rs = db.listaProjetosTodosRS();
        DefaultTableModel T;
        T = returndata(rs);
        jTable1.setModel(T);
        PrjLst.getViewport().add(jTable1);
        lastPressed = ListAllBtn;
        jButtonRf.doClick();
    }//GEN-LAST:event_ListAllBtnActionPerformed

    private void ListOwnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOwnBtnActionPerformed
        ResultSet rs = db.listaProjetosDonoRS(UsernameTxtF.getText());
        DefaultTableModel T;
        T = returndata(rs);
        jTable1.setModel(T);
        PrjLst.getViewport().add(jTable1);
        lastPressed = ListOwnBtn;
        jButtonRf.doClick();
    }//GEN-LAST:event_ListOwnBtnActionPerformed

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed

        String msg = MessageTxtArea.getText();
        String user = UsernameTxtF.getText();
        int idp = Integer.valueOf(OpenTxtFld.getText());
        String result;
        try {
            result = db.mandarMsg(user, idp, msg);
            StatusLbl.setForeground(Color.green);
            StatusLbl.setText(result);
        } catch (SQLException ex) {
            Logger.getLogger(WikiStarterGUI.class.getName()).log(Level.SEVERE, null, ex);
            StatusLbl.setText("DATABASE ERROR");
        }
    }//GEN-LAST:event_SendBtnActionPerformed

    private void CreatePrjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePrjBtnActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("yy-MM-dd");
        Date date = new Date();
        String dateS = dateFormat.format(date);
        
        
        DateFormat dateFormat2 = new SimpleDateFormat("yy-MM-DD", Locale.ENGLISH);
        int flag = 0;
        int flag2 = 0;
        try {
            Float.valueOf(jTextFieldObjective.getText());
        } catch (NumberFormatException e) {
            flag = 1;
        }
        try{
            dateFormat2.parse(jTextFieldDue.getText());
        }catch(ParseException e){
            flag2 = 1;
        }
        

        if (jTextFieldName.getText().isEmpty() || jTextAreaDescription.getText().isEmpty() || jTextFieldDue.getText().isEmpty()) {
            StatusLblPA.setForeground(Color.red);
            StatusLblPA.setText("Please Fill All Boxes");
        } else if (flag == 1) {
            StatusLblPA.setForeground(Color.red);
            StatusLblPA.setText("Not a Valid Ammout");
        } else if (flag2 == 1) {
            StatusLblPA.setForeground(Color.red);
            StatusLblPA.setText("Wrong Date Format");
        } else {
            StatusLblPA.setForeground(Color.green);
       StatusLblPA.setText(db.criarProjeto(jTextFieldName.getText(), UsernameTxtF.getText(), jTextAreaDescription.getText(), dateS, jTextFieldDue.getText(), Float.valueOf(jTextFieldObjective.getText())));
        }
        jButtonRf.doClick();
    }//GEN-LAST:event_CreatePrjBtnActionPerformed

    private void PersonalAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalAreaBtnActionPerformed
        LoginPanel.setVisible(false);
        MainPanel.setVisible(false);
        PersonalArea.setVisible(true);
        UsernameTxtFPA.setText(UsernameTxtF.getText());
        ResultSet rs = db.listaProjetosDonoRS(UsernameTxtF.getText());
        DefaultTableModel T;
        T = returndata(rs);
        jTable2.setModel(T);
        PrjLst1.getViewport().add(jTable2);
        jButtonRf.doClick();
    }//GEN-LAST:event_PersonalAreaBtnActionPerformed

    private void MainAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainAreaBtnActionPerformed
        LoginPanel.setVisible(false);
        MainPanel.setVisible(true);
        PersonalArea.setVisible(false);
        ResultSet rs = db.listaProjetosActuaisRS();
        DefaultTableModel T;
        T = returndata(rs);
        jTable1.setModel(T);
        PrjLst.getViewport().add(jTable1);
        BalanceLbl2.setText(db.consultarSaldo(UsernameTxtFPA.getText()));
        lastPressed = ListActiveBtn;
        jButtonRf.doClick();
    }//GEN-LAST:event_MainAreaBtnActionPerformed

    private void LogoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtn1ActionPerformed
        LogoutBtn.doClick();
    }//GEN-LAST:event_LogoutBtn1ActionPerformed

    private void jButtonReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReplyActionPerformed
              
        try {
            StatusLblPA.setForeground(Color.blue);
            StatusLblPA.setText(db.responderMensagens(UsernameTxtF1.getText(),Integer.valueOf(globalID), Integer.valueOf(jList2.getSelectedValue()), jTextArea1.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(WikiStarterGUI.class.getName()).log(Level.SEVERE, null, ex);
            StatusLblPA.setForeground(Color.red);
            StatusLblPA.setText("ERROR IN DB");
        }
    }//GEN-LAST:event_jButtonReplyActionPerformed

    private void jButtonGMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGMActionPerformed
       //listar mensagens
        DefaultListModel model;
        globalID = OpenTxtFld.getText();
        model = db.mostrarMensagensLST(Integer.valueOf(OpenTxtFld.getText()));
        jList2.setModel(model);
        jList2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jList2.setSelectedIndex(0);
        jScrollPane3.getViewport().add(jList2);
        
        jTextArea3.setText(db.mostrarVotosProj(Integer.valueOf(OpenTxtFld.getText())));
    }//GEN-LAST:event_jButtonGMActionPerformed

    private void jButtonGM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGM1ActionPerformed
        jTextArea2.setText(db.mostrarMensagen(Integer.valueOf(jList2.getSelectedValue())));
        jTextArea1.setText(db.mostrarResposta(Integer.valueOf(jList2.getSelectedValue())));
    }//GEN-LAST:event_jButtonGM1ActionPerformed

    private void jButtonRfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRfActionPerformed
        try {
            StatusLbl.setText(db.updateVAL());
        } catch (SQLException ex) {
            Logger.getLogger(WikiStarterGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRfActionPerformed

    private void ListOwnBtnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOwnBtnPActionPerformed
        UsernameTxtFPA.setText(UsernameTxtF.getText());
        ResultSet rs = db.listaProjetosDonoRS(UsernameTxtF.getText());
        DefaultTableModel T;
        T = returndata(rs);
        jTable2.setModel(T);
        PrjLst1.getViewport().add(jTable2);
        jButtonRf.doClick();
        jButtonRf.doClick();
    }//GEN-LAST:event_ListOwnBtnPActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int flag =0;
        
        try {
            Float.valueOf(jTextField2.getText());
        } catch (NumberFormatException e) {
            flag = 1;
        }
        if(flag == 0){
            StatusLblPA.setText(db.adicionarRecompensas(Integer.valueOf(OpenTxtFld.getText()), jTextField1.getText(), Float.valueOf(jTextField2.getText())));
        }else{
            StatusLblPA.setText("Invalid Parameters");
        }    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StatusLblPA.setText(db.adicionarVotos(Integer.valueOf(OpenTxtFld.getText()), jTextField3.getText()));
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CancelProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelProjActionPerformed
        try {
            StatusLblPA.setText(db.cancelarProjeto(UsernameTxtF.getText(), Integer.valueOf(OpenTxtFld.getText())));
        } catch (SQLException ex) {
            Logger.getLogger(WikiStarterGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancelProjActionPerformed

    
    
    //ReturnData do Main
    public DefaultTableModel returndata(ResultSet rs) {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                System.out.println(row);
                try {
                    rs.absolute(row + 1);
                    String temp = rs.getString("ID");
                    OpenTxtFld.setText(temp);
                    jLabel6.setText(temp);

                } catch (SQLException ex) {
                    Logger.getLogger(WikiStarterGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                return false;
            }
        };
        {
            try {

                ResultSetMetaData rsMD = rs.getMetaData();
                int contcolum = rsMD.getColumnCount();
                Object[] objeto = new Object[contcolum];
                for (int i = 0; i < contcolum; i++) {
                    objeto[i] = rsMD.getColumnLabel(i + 1);
                }
                model.setColumnIdentifiers(objeto);
                rs.first();
                rs.beforeFirst();
                while (rs.next()) {
                    Object[] dadosFila = new Object[model.getColumnCount()];
                    for (int i = 0; i < model.getColumnCount(); i++) {
                        dadosFila[i] = rs.getObject(i + 1);
                    }
                    model.addRow(dadosFila);
                }

            } catch (Exception e) {
                System.out.println(e);
            }
        }

        return model;
    }

    public DefaultTableModel returndataPArea(ResultSet rs) {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                System.out.println(row);
                try {
                    rs.absolute(row + 1);
                    String temp = rs.getString("ID");
                    OpenTxtFld.setText(temp);
                    jLabel6.setText(temp);

                } catch (SQLException ex) {
                    Logger.getLogger(WikiStarterGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                return false;
            }
        };
        {
            try {

                ResultSetMetaData rsMD = rs.getMetaData();
                int contcolum = rsMD.getColumnCount();
                Object[] objeto = new Object[contcolum];
                for (int i = 0; i < contcolum; i++) {
                    objeto[i] = rsMD.getColumnLabel(i + 1);
                }
                model.setColumnIdentifiers(objeto);
                rs.first();
                rs.beforeFirst();
                while (rs.next()) {
                    Object[] dadosFila = new Object[model.getColumnCount()];
                    for (int i = 0; i < model.getColumnCount(); i++) {
                        dadosFila[i] = rs.getObject(i + 1);
                    }
                    model.addRow(dadosFila);
                }

            } catch (Exception e) {
                System.out.println(e);
            }
        }

        return model;
    }

    String globalID;
    JList list;
    DBInterface db;
    private javax.swing.JButton lastPressed;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmmountFld;
    private javax.swing.JLabel BalanceLbl;
    private javax.swing.JLabel BalanceLbl2;
    private javax.swing.JButton CancelProj;
    private javax.swing.JButton CreatePrjBtn;
    private javax.swing.JLabel DescTxtArea;
    private javax.swing.JTextArea DescriptionArea;
    private javax.swing.JLabel ErrorLbl;
    private javax.swing.JButton ListActiveBtn;
    private javax.swing.JButton ListAllBtn;
    private javax.swing.JButton ListOldBtn;
    private javax.swing.JButton ListOwnBtn;
    private javax.swing.JButton ListOwnBtnP;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton LogoutBtn1;
    private javax.swing.JButton MainAreaBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextArea MessageTxtArea;
    private javax.swing.JButton OpenPrjBtn;
    private javax.swing.JTextField OpenTxtFld;
    private javax.swing.JPasswordField PassworfFld;
    private javax.swing.JPanel PersonalArea;
    private javax.swing.JButton PersonalAreaBtn;
    private javax.swing.JButton PledgeBtn;
    private javax.swing.JLabel PrjAmmoutLbl;
    private javax.swing.JLabel PrjDueLbl;
    private javax.swing.JLabel PrjDueLbl1;
    private javax.swing.JLabel PrjIdLbl;
    private javax.swing.JScrollPane PrjLst;
    private javax.swing.JScrollPane PrjLst1;
    private javax.swing.JLabel PrjNameLbl;
    private javax.swing.JLabel PrjNameLbl1;
    private javax.swing.JLabel PrjObjLbl;
    private javax.swing.JLabel PrjObjLbl1;
    private javax.swing.JLabel PrjOwnerLbl;
    private javax.swing.JLabel PrjTblLbl;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JTextArea RewardsArea;
    private javax.swing.JToggleButton SendBtn;
    private javax.swing.JLabel SendMsgLbl;
    private javax.swing.JLabel StatusLbl;
    private javax.swing.JLabel StatusLblPA;
    private javax.swing.JTextField TitleTxtF;
    private javax.swing.JTextField TitleTxtF1;
    private javax.swing.JTextField TitleTxtF2;
    private javax.swing.JTextField UsernameFld;
    private javax.swing.JLabel UsernameLbl;
    private javax.swing.JLabel UsernameTxtF;
    private javax.swing.JLabel UsernameTxtF1;
    private javax.swing.JLabel UsernameTxtFPA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGM;
    private javax.swing.JButton jButtonGM1;
    private javax.swing.JButton jButtonReply;
    private javax.swing.JButton jButtonRf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldDue;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldObjective;
    // End of variables declaration//GEN-END:variables

}
